trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'users-api/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
